### ISSUE TITLE
Python error when cloning: AttributeError: 'HTTPResponse' object has no attribute 'geturl'

### ISSUE THREAD

**Issue by plafosse** [dulwich/dulwich#702]
I'm getting the following error which seems to have been introduced by https://github.com/dulwich/dulwich/commit/5148c0c22d8a35ad094b431b116a35b4fa41cba0#diff-28cd0777376826bef5605561210673e2
```/usr/local/lib/python3.7/site-packages/dulwich-0.19.12-py3.7.egg/dulwich/client.py in _http_request(self, url, headers, data, allow_compression)
   1518
   1519         resp.content_type = resp.getheader("Content-Type")
-> 1520         resp_url = resp.geturl()
   1521         resp.redirect_location = resp_url if resp_url != url else ''
   1522

AttributeError: 'HTTPResponse' object has no attribute 'geturl'```

**Comment by jelmer** [comment]
You need a newer version of urllib3; older versions don't have geturl()

**Comment by plafosse** [comment]
Thanks for the response, adding a version check might be handy. I googled that error and couldn't find anything.

**Comment by jelmer** [comment]
There is a version check in setup.py; I'm open to patches adding a run-time check as well, though we don't really do that for our other dependencies either.

**Comment by havatv** [comment]
After the "merge" of #750, earlier versions of urllib3 than 1.23 are supported again, meaning that dulwich can be used on Ubuntu 18.04.
